export const GET_CHANNELS_REQUEST = 'GET_CHANNELS_REQUEST';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAILURE = 'GET_CHANNELS_FAILURE';

export const GET_LAST_OPENED_CHANNEL_REQUEST = 'GET_LAST_OPENED_CHANNEL_REQUEST';
export const GET_LAST_OPENED_CHANNEL_SUCCESS = 'GET_LAST_OPENED_CHANNEL_SUCCESS';
export const GET_LAST_OPENED_CHANNEL_FAILURE = 'GET_LAST_OPENED_CHANNEL_FAILURE';

export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';

export const ADD_CHANNEL_REQUEST = 'ADD_CHANNEL_REQUEST';
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const ADD_CHANNEL_FAILURE = 'ADD_CHANNEL_FAILURE';

export const GET_CHANNEL_BY_TITLE_REQUEST = 'GET_CHANNEL_BY_TITLE_REQUEST';
export const GET_CHANNEL_BY_TITLE_SUCCESS = 'GET_CHANNEL_BY_TITLE_SUCCESS';
export const GET_CHANNEL_BY_TITLE_FAILURE = 'GET_CHANNEL_BY_TITLE_FAILURE';