export const SHOW_LOG_IN_DIALOG = 'SHOW_LOG_IN_DIALOG';
export const HIDE_LOG_IN_DIALOG = 'HIDE_LOG_IN_DIALOG';
export const SHOW_SIGN_UP_DIALOG = 'SHOW_SIGN_UP_DIALOG';
export const HIDE_SIGH_UP_DIALOG = 'HIDE_SIGH_UP_DIALOG';
export const SHOW_ADD_COMMUNITY_DIALOG = 'SHOW_ADD_COMMUNITY_DIALOG';
export const HIDE_ADD_COMMUNITY_DIALOG = 'HIDE_ADD_COMMUNITY_DIALOG';
export const SHOW_ADD_CHANNEL_DIALOG = 'SHOW_ADD_CHANNEL_DIALOG';
export const HIDE_ADD_CHANNEL_DIALOG = 'HIDE_ADD_CHANNEL_DIALOG';