export const CONNECT_TO_WEBSOCKET_REQUEST = 'CONNECT_TO_WEBSOCKET_REQUEST';
export const CONNECT_TO_WEBSOCKET_SUCCESS = 'CONNECT_TO_WEBSOCKET_SUCCESS';
export const CONNECT_TO_WEBSOCKET_FAILURE = 'CONNECT_TO_WEBSOCKET_FAILURE';
export const SUBSCRIBE_TO_TOPIC_REQUEST = 'SUBSCRIBE_TO_TOPIC_REQUEST';
export const SUBSCRIBE_TO_TOPIC_SUCCESS = 'SUBSCRIBE_TO_TOPIC_SUCCESS';
export const SUBSCRIBE_TO_TOPIC_FAILURE = 'SUBSCRIBE_TO_TOPIC_FAILURE';
export const UNSUBSCRIBE_REQUEST = 'UNSUBSCRIBE_REQUEST';
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
export const UNSUBSCRIBE_FAILURE = 'UNSUBSCRIBE_FAILURE';
export const DISCONNECT_REQUEST = 'DISCONNECT_REQUEST';
export const DISCONNECT_SUCCESS = 'DISCONNECT_SUCCESS';
export const DISCONNECT_FAILURE = 'DISCONNECT_FAILURE';

